### ISSUE TITLE
expect instance has no attribute 'throw'

### ISSUE THREAD

**Issue by tklarryonline** [EastAgile/robber.py#18]
We in Pandoodle are using the latest build from EastAgile/robber.py but still get this error:

```py
AttributeError: expect instance has no attribute 'throw'
```

Is there something wrong with the latest build from `master` branch?

**Comment by tklarryonline** [comment]
@hieueastagile Any thoughts?

**Comment by oyster** [comment]
Cool. Good to see our projects start using some of our open source here :-)

**Comment by hieueastagile** [comment]
@tklarryonline I miss this line
```python
from robber.matchers.exception import *
````
in the `_ init _.py`, that's why it failed, I updated the code in this PR: https://github.com/EastAgile/robber.py/pull/19/files, until it is merged, you can fix it temporarily by re-install your robber.py to this specific branch instead of master
```bash
pip install -e git+https://github.com/EastAgile/robber.py@integration-tests-for-exception-matcher#egg=robber
```
Sorry for this inconvenience :D. I already tested it in my local, so it should work now :D.

**Comment by tklarryonline** [comment]
Thanks @hieueastagile :)
